---
create_user: madeo
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'nano', 'git', 'ufw', 'apt-transport-https', 'software-properties-common', 'ca-certificates', 'gnupg-agent', 'jq']

  - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common