---
- hosts: all
  become: true

  tasks:
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --control-plane-endpoint {{ loadbalancer_ip }}:{{ loadbalancer_port }} --upload-certs  --node-name {{ node_name }} --pod-network-cidr=192.168.0.0/16

    - name: Setup kubeconfig for k8s user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/k8s/.kube
        - cp -i /etc/kubernetes/admin.conf /home/k8s/.kube/config
        - chown k8s:k8s /home/k8s/.kube/config

    - name: Install calico pod network
      become: false
      command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
