---
create_user: docker
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [
  'curl',
  'ufw',
  'net-tools',
  'apt-transport-https',
  'software-properties-common',
  'jq',
  'bridge-utils',
  'unattended-upgrades'
]