---
- hosts: all
  become: true
  vars:
    haproxy_ip: "{{ node_ip }}"
    masternodes: "{{ masternodes }}"
  vars_files:
    - default.yml

  tasks:
    # Install Packages for HaProxy
    - name: Update apt
      apt: update_cache=yes

    - name: Install required system packages
      apt: name={{ sys_packages }} state=latest

    - name: Copy haproxy config
      template:
        src: haproxy.cfg.j2
        dest: "/etc/haproxy/haproxy.cfg"

    - name: start haproxy
      service:
        name: "haproxy"
        state: restarted