# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure(2) do |config|
  NodeCount = 1

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    ip = "192.168.0.21#{i}"
    config.vm.define "kworker#{i}" do |workernode|
      workernode.vm.hostname = "kworker#{i}"
      workernode.vm.box = "peru/ubuntu-20.04-server-amd64"
      workernode.vm.network :public_network, :dev => 'br0', :type => 'bridge', ip: ip
      workernode.vm.provider :libvirt do |v|
          v.memory = 2048
          v.cpus = 1
          v.host = "homelab"
          v.username = "madeo"
          v.driver = "kvm"
          v.connect_via_ssh = true
          v.id_ssh_key_file = "/home/matteo/.ssh/id_rsa"
      end
    end
  end

end